# .github/workflows/ci.yml

name: Java CI com Maven e Artefato

on:
  push:
    branches: [ "main" ] # O pipeline será ativado apenas em pushes para a branch 'main'

jobs:
  build_test_and_package:
    runs-on: ubuntu-latest # O job rodará na máquina virtual Ubuntu

    steps:
    - uses: actions/checkout@v3 # Passo 1: Clona o código do repositório
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Usa a versão 17 do JDK
        distribution: 'temurin'
        cache: maven # Habilita o cache do Maven para acelerar builds futuros

    - name: Construir, Testar e Empacotar com Maven
      run: mvn -B package --file pom.xml # Passo 2: Executa o ciclo de vida do Maven. O 'package' já inclui as fases 'compile' e 'test'.

    - name: Gerar Artefato JAR
      uses: actions/upload-artifact@v4 # Passo 3: Salva o JAR como um artefato no pipeline
      with:
        name: boardgame-catalog-jar # Nome do artefato
        path: target/*.jar # Caminho do arquivo a ser salvo